import os

import toml

config = toml.load(".secrets/secrets.toml")


WIX_CLIENT_ID = config["WIX"]["WIX_CLIENT_ID"]
CLIENT_ID = config["WIX"]["CLIENT_ID"]
CLIENT_SECRET = config["WIX"]["CLIENT_SECRET"]

FASTAPI_AUTH = config["FASTAPI"]["AUTH"]
FASTAPI_BEARER_TOKEN = config["FASTAPI"]["BEARER_TOKEN"]
FASTAPI_MIDDLEWARE_SECRECT_KEY = config["FASTAPI"]["MIDDLEWARE_SECRECT_KEY"]

END_POINT = config["EDGE_FUNCTIONS"]["END_POINT"]
BEARER_TOKEN = config["EDGE_FUNCTIONS"]["BEARER_TOKEN"]
EMAIL = config["EDGE_FUNCTIONS"]["EMAIL"]
PASSWORD = config["EDGE_FUNCTIONS"]["PASSWORD"]
X_REGION = config["EDGE_FUNCTIONS"]["X_REGION"]


